apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: redis-docker-deployment
  labels:
    app: redis-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-docker
  template:
    metadata:
      labels:
        app: redis-docker
    spec:
      containers:
      - name: redis-docker
        image: redis
        ports:
        - containerPort: 6379
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
